/*
 * Copyright 2017 International Business Machines
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * SNAP GPU Example
 *
 * Demonstration how to use SNAP with a GPU.
 * Data is generated by the FPGA (vector of size N) and GPU get this data to
 * perform an addition of this vector with itself before sending back the result
 * in the HOST memory.
 * 
 */

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <getopt.h>
#include <malloc.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <assert.h>

#include <snap_tools.h>
#include <libsnap.h>
#include <action_create_vector.h>
#include <snap_hls_if.h>

int verbose_flag = 0;


static const char *mem_tab[] = { "HOST_DRAM", "CARD_DRAM", "TYPE_NVME" };


// Function that fills the MMIO registers / data structure 
// these are all data exchanged between the application and the action
static void snap_prepare_gpu_example(struct snap_job *cjob,
				 struct gpu_example_job *mjob,
	             int size,
				 void *addr_out,
				 uint32_t size_out,
				 uint8_t type_out)
{
	fprintf(stderr, "  prepare gpu_example job of %ld bytes size\n", sizeof(*mjob));

	assert(sizeof(*mjob) <= SNAP_JOBSIZE);
	memset(mjob, 0, sizeof(*mjob));

    mjob->vectorSize = size;
	
    // Setting output params : where result will be written in host memory
	snap_addr_set(&mjob->out, addr_out, size_out, type_out,
		      SNAP_ADDRFLAG_ADDR | SNAP_ADDRFLAG_DST |
		      SNAP_ADDRFLAG_END);

	snap_job_set(cjob, mjob, sizeof(*mjob), NULL, 0);
}

/* main program of the application for the hls_helloworld example        */
/* This application will always be run on CPU and will call either       */
/* a software action (CPU executed) or a hardware action (FPGA executed) */
int main(int argc, char *argv[])
{
	// Init of all the default values used 
	int ch = 0;
	int card_no = 0;
	struct snap_card *card = NULL;
	struct snap_action *action = NULL;
	char device[128];
	struct snap_job cjob;
	struct gpu_example_job mjob;
	const char *input = NULL;
	const char *output = NULL;
	unsigned long timeout = 600;
	const char *space = "CARD_RAM";
    uint64_t vectorSize = 0;
	uint32_t  *obuff = NULL;
	uint32_t type_out = SNAP_ADDRTYPE_HOST_DRAM;
	uint64_t addr_out = 0x0ull;
	int verify = 0;
	int exit_code = EXIT_SUCCESS;
	snap_action_flag_t action_irq = (SNAP_ACTION_DONE_IRQ | SNAP_ATTACH_IRQ);

	// collecting the command line arguments
	while (1) {
		int option_index = 0;
		static struct option long_options[] = {
			{ "input",	 required_argument, NULL, 'i' },
			{ "output",	 required_argument, NULL, 'o' },
		};

		ch = getopt_long(argc, argv,
                                 "C:i:o:A:a:D:d:s:t:XNVvh",
				 long_options, &option_index);
		if (ch == -1)
			break;

		switch (ch) {
		case 'C':
			card_no = strtol(optarg, (char **)NULL, 0);
			break;
		case 'i':
			input = optarg;
			break;
		case 'o':
			output = optarg;
			break;
			/* output data */
		case 'D':
			space = optarg;
			if (strcmp(space, "CARD_DRAM") == 0)
				type_out = SNAP_ADDRTYPE_CARD_DRAM;
			else if (strcmp(space, "HOST_DRAM") == 0)
				type_out = SNAP_ADDRTYPE_HOST_DRAM;
			else {
				exit(EXIT_FAILURE);
			}
			break;
		case 'd':
			addr_out = strtol(optarg, (char **)NULL, 0);
			break;
                case 's':
                        //size = __str_to_num(optarg);
                        break;
                case 't':
                        timeout = strtol(optarg, (char **)NULL, 0);
                        break;		
                case 'X':
			verify++;
			break;
                case 'N':
                        action_irq = 0;
                        break;
		}
	}

    if (input != NULL) {
        vectorSize = atoi(input);
    }

	/* if output file is defined, use that as output */
	if (output != NULL) {
		size_t set_size = vectorSize*sizeof(uint32_t);

		/* Allocate in host memory the place to put the text processed */
		obuff = snap_malloc(set_size); //64Bytes aligned malloc
		memset(obuff, 0x0, set_size);

		// prepare params to be written in MMIO registers for action
		type_out = SNAP_ADDRTYPE_HOST_DRAM;
		addr_out = (unsigned long)obuff;
	}


	/* Display the parameters that will be used for the example */
	printf("PARAMETERS:\n"
	       "  input:       %s\n"
	       "  output:      %s\n"
	       "  type_out:    %x %s\n"
	       "  addr_out:    %016llx\n"
	       "  size_out:    %lu\n",
	       input  ? input  : "unknown", output ? output : "unknown",
	       type_out, mem_tab[type_out], (long long)addr_out,
	       vectorSize*sizeof(uint32_t));


	// Allocate the card that will be used
	snprintf(device, sizeof(device)-1, "/dev/cxl/afu%d.0s", card_no);
	card = snap_card_alloc_dev(device, SNAP_VENDOR_ID_IBM,
				   SNAP_DEVICE_ID_SNAP);

	// Attach the action that will be used on the allocated card
	action = snap_attach_action(card, GPU_EXAMPLE_ACTION_TYPE, action_irq, 60);

	// Fill the stucture of data exchanged with the action
	snap_prepare_gpu_example(&cjob, &mjob,vectorSize,(void *)addr_out, vectorSize*sizeof(uint32_t), type_out);

	// Call the action will:
	snap_action_sync_execute_job(action, &cjob, timeout);

	/* If the output buffer is in host DRAM we can write it to a file */
	if (output != NULL) {
		fprintf(stdout, "writing output data %p %lu bytes to %s\n",
			obuff, vectorSize*sizeof(uint32_t), output);
        for (uint32_t i = 0; i<vectorSize; i++){
            fprintf(stdout, "%d \n",obuff[i]);
        }

		__file_write(output, (uint8_t *)obuff, vectorSize*sizeof(uint32_t));
	}

	// Detach action + disallocate the card
	snap_detach_action(action);
	snap_card_free(card);

	__free(obuff);
	exit(exit_code);

}
