#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2016,2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#
snapdir=$(dirname $(readlink -f "$BASH_SOURCE")) # path containing this script
PATH=$snapdir:$PATH

snap_config=$snapdir/\.snap_config

simulator=`grep SIMULATOR $snap_config|cut -d = -f 2 |tr -d '"'`

cd hardware/sim
if [ $simulator == "xsim" ]; then
  if [ -d "xsim" ]; then
    ./xsimtrace
  else
    echo "Please launch a simulation (make sim) prior to see traces"
  fi
fi
if [ $simulator == "irun" ]; then
  if [ -d "ies" ]; then
    ./iruntrace
  else
    echo "Please launch a simulation (make sim) prior to see traces"
  fi
fi

cd ../..
