#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2016,2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#
snapdir=$(dirname $(readlink -f "$BASH_SOURCE")) # path containing this script
PATH=$snapdir:$PATH

snap_env_sh=$snapdir/snap_env.sh

unset PSL_DCP
unset PSL_IP
unset HDK_ROOT
unset ACTION_ROOT
unset PSLSE_ROOT
unset TIMING_LABLIMIT
unset ILA_SETUP_FILE
unset DCP_ROOT
unset config_script
unset snap_env_info

TIMING_LABLIMIT_DEFAULT="-200"

while [[ $# -gt 0 ]]; do
  case "$1" in
    "config")
      snap_env_info=y
      shift
      ;;
    "ignore_action_root")
      ignore_action_root=y
      shift
      ;;
    *)
      config_script=$1
      shift
      ;;
  esac
done

if [ -e "$config_script" ]; then
  source $config_script
fi

if [ -e "$snap_env_sh" ]; then
  source "$snap_env_sh"
else
  touch "$snap_env_sh"
fi

unset SETUP_DONE
while [ -z "$SETUP_DONE" ]; do
  SETUP_WARNING=""
  SETUP_INFO=""
  SETUP_EMPTY=""
  echo "======================================================="
  echo "== SNAP ENVIRONMENT SETUP                            =="
  echo "======================================================="


  ####### checking Xilinx Vivado
  if [ ! -d "$XILINX_VIVADO" ]; then
    SETUP_WARNING="$SETUP_WARNING\n### WARNING ### XILINX_VIVADO  (set to  \"$XILINX_VIVADO\") is not pointing to a directory:"
    SETUP_WARNING="$SETUP_WARNING\n    Please source settings64.sh from your Vivado installation"
  fi
  if [ -z "$XILINXD_LICENSE_FILE" ]; then
    SETUP_WARNING="$SETUP_WARNING\n### WARNING ### XILINXD_LICENSE_FILE is not set:"
    SETUP_WARNING="$SETUP_WARNING\n    The following command needs to be executed before initiating hardware builds:"
    SETUP_WARNING="$SETUP_WARNING\n    export XILINXD_LICENSE_FILE=<pointer to Vivado license>"
  fi

  # printing Vivado version
  if [ -z `which vivado 2> /dev/null` ]; then
    SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Path to vivado is not set:"
    SETUP_WARNING="$SETUP_WARNING\n    Please add to environment variable \$PATH"
  else
    echo "Path to vivado          is set to: `which vivado`"
    echo "Vivado version          is set to: `vivado -version|head -n1`"
  fi


  ####### checking FPGA card setup
  # Note: Card N250SP is currently in preparation phase
  if [ "$FPGACARD" == "N250SP" ]; then
    SETUP_INFO="$SETUP_INFO\n### INFO ### Support for the selected CAPI2.0 FPGA card N250SP is currently in preparation phase."
    echo "=====Checking path to PSL for N250SP============"
    echo "PSL_IP                  is set to: \"$PSL_IP\""
    RESP=`grep PSL_IP $snap_env_sh`
    if [ -z "$RESP" ]; then
      echo "#export PSL_IP=" >> $snap_env_sh
    fi
    if [ -z "$PSL_IP" ]; then
      SETUP_INFO="$SETUP_INFO\n### INFO ### For image build the environment variable PSL_IP must point to the directory containing the PSL IP."
    fi
    echo "=====Checking path to Board support for N250SP============"
    if [ -d "$HDK_ROOT/boards/N250SP" ]; then
      echo "HDK_ROOT                is set to: \"$HDK_ROOT\""
    elif [ -d "$snapdir/hardware/hdk/boards/N250SP" ]; then
      echo "Will use hdk found in $snapdir/hardware/hdk"
    else
      SETUP_INFO="$SETUP_INFO\n### INFO ### For image build the environment variable HDK_ROOT must point to the directory containing the HDK definitions."
      SETUP_INFO="$SETUP_INFO\n### INFO ### or $snapdir/hardware/hdk needs to contain the HDK definitions."
    fi
  ####### checking path to PSL design checkpoint
  # Note: CLOUD_USER_FLOW is defined via snap_config
  elif [ "$CLOUD_USER_FLOW" == "TRUE" ]; then
    SETUP_INFO="$SETUP_INFO\n### INFO ### Cloud user flow is skipping PSL_DCP check."
  elif [ "$IGNORE_CHECK_PSL" == "TRUE" ]; then
    SETUP_INFO="$SETUP_INFO\n### INFO ### Skipping PSL_DCP check because environment variable IGNORE_CHECK_PSL is set to TRUE."
  else
    echo "=====Checking path to PSL design checkpoint============"
    echo "PSL_DCP                 is set to: \"$PSL_DCP\""
    RESP=`grep PSL_DCP $snap_env_sh`
    if [ -z "$RESP" ]; then
      echo "#export PSL_DCP=" >> $snap_env_sh
    fi
    if [ -e "$PSL_DCP" ]; then
      # checking card type for PSL design checkpoint
      PSL_DCP_TYPE=`$snapdir/hardware/snap_check_psl $FPGACARD $PSL_DCP`
      if [ "$PSL_DCP_TYPE" != "$FPGACARD" ]; then
        if [[ "$PSL_DCP_TYPE" == *"OUTDATED"* ]]; then
          SETUP_INFO="$SETUP_INFO\n### INFO ### PSL_DCP for $FPGACARD is pointing to an outdated design checkpoint, image build will not be allowed."
        else
          SETUP_INFO="$SETUP_INFO\n### INFO ### PSL_DCP is pointing to a checkpoint for a $PSL_DCP_TYPE card while FPGACARD is set to $FPGACARD, image build will not be allowed."
        fi
      fi
    else
      SETUP_INFO="$SETUP_INFO\n### INFO ### For image build the environment variable PSL_DCP must point to the CAPI PSL Checkpoint file (b_route_design.dcp)."
    fi
  fi


  ####### checking path to PSLSE (only if simulation is enabled)
  # Note: SIMULATOR is defined via snap_config
  if [ $SIMULATOR != "nosim" ]; then
    echo "=====Simulation setup: Setting up PSLSE version=========="
    if [ "$FPGACARD" == "N250SP" ]; then
      PSLVER="9"
    else
      PSLVER="8"
    fi
    echo "Setting PSLVER                 to: \"$PSLVER\""
    sed -i '/export[ ^]*PSLVER[ ^]*=/ d' $snap_env_sh
    echo "export PSLVER=$PSLVER" >> $snap_env_sh
    echo "=====Simulation setup: Checking path to PSLSE=========="
    echo "PSLSE_ROOT              is set to: \"$PSLSE_ROOT\""
    RESP=`grep PSLSE_ROOT $snap_env_sh`
    if [ -z "$RESP" ]; then
      echo "export PSLSE_ROOT=" >> $snap_env_sh
    fi
    if [ -z "$PSLSE_ROOT" ]; then
      SETUP_EMPTY="$SETUP_EMPTY\n  PSLSE_ROOT"
    elif [ ! -d "$PSLSE_ROOT" ]; then
      SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Path to PSLSE not set properly."
      SETUP_WARNING="$SETUP_WARNING\n    For simulation please clone PSL Simulation Environment"
      SETUP_WARNING="$SETUP_WARNING\n    from https://github.com/ibm-capi/pslse"
      SETUP_WARNING="$SETUP_WARNING\n    and let \$PSLSE_ROOT point to it."
      SETUP_WARNING="$SETUP_WARNING\n    Please set Simulator to 'nosim' if you do not intend to run simulation."
    fi
  fi


  ####### SNAP path variables
  echo "=====ACTION ROOT setup================================="
  unset AR
  if [ -n "$HDL_EXAMPLE" ]; then
    AR='${SNAP_ROOT}/actions/hdl_example'
  elif [ -n "$HDL_NVME_EXAMPLE" ]; then
    AR='${SNAP_ROOT}/actions/hdl_nvme_example'
  elif [ -n "$HLS_MEMCOPY" ]; then
    AR='${SNAP_ROOT}/actions/hls_memcopy'
  elif [ -n "$HLS_SPONGE" ]; then
    AR='${SNAP_ROOT}/actions/hls_sponge'
  elif [ -n "$HLS_HASHJOIN" ]; then
    AR='${SNAP_ROOT}/actions/hls_hashjoin'
  elif [ -n "$HLS_SEARCH" ]; then
    AR='${SNAP_ROOT}/actions/hls_search'
  elif [ -n "$HLS_BFS" ]; then
    AR='${SNAP_ROOT}/actions/hls_bfs'
  elif [ -n "$HLS_INTERSECT" ]; then
    AR='${SNAP_ROOT}/actions/hls_intersect'
  elif [ -n "$HLS_NVME_MEMCOPY" ]; then
    AR='${SNAP_ROOT}/actions/hls_nvme_memcopy'
  elif [ -n "$HLS_HELLOWORLD" ]; then
    AR='${SNAP_ROOT}/actions/hls_helloworld'
  fi
  if [ -z "$AR" ] && [ -n "$ACTION_ROOT" ]; then
    AR=$ACTION_ROOT
    echo "ACTION_ROOT             is set to: \"$ACTION_ROOT\""
    SETUP_INFO="$SETUP_INFO\n### INFO ### Kept ACTION_ROOT from previous configuration."
  else
    echo "Setting ACTION_ROOT            to: \"$AR\""
    sed -i '/export[ ^]*ACTION_ROOT[ ^]*=/ d' $snap_env_sh
    echo "export ACTION_ROOT=$AR" >> $snap_env_sh
  fi

  if [ -z "$AR" ] && [ "$ignore_action_root" != "y" ]; then
    SETUP_EMPTY="$SETUP_EMPTY\n  ACTION_ROOT"
  else
    SNAP_ROOT=$snapdir
    eval ACTION_ROOT=$AR
    if [ "$ignore_action_root" == "y" ]; then
      SETUP_INFO="$SETUP_INFO\n### INFO ### Skipping ACTION_ROOT check"
    elif [ ! -d "$ACTION_ROOT" ] && ( ( [ -z `echo "x$ACTION_ROOT" | grep -i /HLS` ] && [ "${HLS_SUPPORT^^}" != "TRUE" ] ) || [ `basename "x$ACTION_ROOT"` != "vhdl" ] ); then
      SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Please make sure that ACTION_ROOT points to an existing directory."
    fi
  fi


  ####### settings for ILA Debug
  # Note: ILA_DEBUG is defined via snap_config
  if [ "$ILA_DEBUG" == "TRUE" ]; then
    echo "=====ILA Debug setup==================================="
    echo "ILA_SETUP_FILE          is set to: \"$ILA_SETUP_FILE\""
    RESP=`grep ILA_SETUP_FILE $snap_env_sh`
    if [ -z "$RESP" ]; then
      echo "export ILA_SETUP_FILE=" >> $snap_env_sh
    fi
    if [ -z "$ILA_SETUP_FILE" ]; then
      SETUP_EMPTY="$SETUP_EMPTY\n  ILA_SETUP_FILE"
    else
      if [ `echo "$ILA_SETUP_FILE" | tr a-z A-Z` = "TRUE" ] && [ ! -e "$ILA_SETUP_FILE" ]; then
        SETUP_WARNING="$SETUP_WARNING\n### WARNING ### ILA_DEBUG is set to $ILA_DEBUG but ILA_SETUP_FILE (set to \"$ILA_SETUP_FILE\") is not pointing to a file!"
      fi
    fi
  fi


  ####### settings for Partial Reconfiguration flow
  # Note: USE_PRFLOW is defined via snap_config
  if [ "$USE_PRFLOW" == "TRUE" ]; then
    echo "=====PR flow setup====================================="
    RESP=`grep DCP_ROOT $snap_env_sh`
    if [ -z "$RESP" ]; then
      echo "export DCP_ROOT=" >> $snap_env_sh
    fi
    echo "DCP_ROOT                is set to: \"$DCP_ROOT\""
    if [ -z "$DCP_ROOT" ]; then
      SETUP_EMPTY="$SETUP_EMPTY\n  DCP_ROOT"
    fi
  fi


  ####### checking TIMNG LIMITS setup
  if [ -z "$TIMING_LABLIMIT" ]; then
    $TIMING_LABLIMIT="$TIMING_LABLIMIT_DEFAULT"
    sed -i '/export[ ^]*TIMING_LABLIMIT[ ^]*=/ d' $snap_env_sh
    echo "export TIMING_LABLIMIT=\"$TIMING_LABLIMIT_DEFAULT\"" >> $snap_env_sh
    SETUP_INFO="$SETUP_INFO\n### INFO ### Timing limit for FPGA image build got set to default value $TIMING_LABLIMIT_DEFAULT"
  fi
    SETUP_INFO="$SETUP_INFO\n### INFO ### Support for the selected CAPI2.0 FPGA card N250SP is currently in preparation phase."
  echo "=====Timing limit for FPGA image build in ps============"
  echo "TIMING_LABLIMIT         is set to: \"$TIMING_LABLIMIT\""


  ####### Cadence simulation setup:
  # Note: SIMULATOR is defined via snap_config
  if [ "$SIMULATOR" == "irun" ]; then
    echo "=====Cadence simulation setup=========================="

    if [ -z `which irun 2> /dev/null` ]; then
      SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Path to irun not set, Cadence simulation won't work"
    else
      echo "Path to irun                   is: \"`which irun`\""
      # checking version
      echo "irun version                   is: \"$(irun -version| cut -f 3)\""
      if [ -z "$CDS_INST_DIR" ]; then
        SETUP_WARNING="$SETUP_WARNING\n### WARNING ### SIMULATOR is $SIMULATOR but CDS_INST_DIR is not set. Simulation may not work."
      fi
      echo "CDS_INST_DIR            is set to: \"$CDS_INST_DIR\""
    fi
    if [ -f "$IES_LIBS/cds.lib" ]; then
      echo "cds.lib (IES_LIBS)       found in: \"$IES_LIBS\""
    else
      SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Cannot find cds.lib in IES_LIBS=$IES_LIBS. Cadence compilation won't work."
    fi
    if [ -z "$CDS_LIC_FILE" ] && [ -z "$LM_LICENSE_FILE" ]; then
      SETUP_WARNING="$SETUP_WARNING\n### WARNING ### Cadence license not defined with CDS_LIC_FILE or LM_LICENSE_FILE. Simulation may not work."
    else
      if [ -n "$CDS_LIC_FILE" ]; then
        echo "CDS_LIC_FILE            is set to: \"$CDS_LIC_FILE\""
      fi
      if [ -n "$LM_LICENSE_FILE" ]; then
        echo "LM_LICENSE_FILE         is set to: \"$LM_LICENSE_FILE\""
      fi
    fi
  fi

  # Note: NVME_USED is defined via snap_config
  if [[ "$NVME_USED" == "TRUE" ]]; then
    echo "=====Denali setup======================================"
    if [ -z "$DENALI" ]; then
      SETUP_INFO="$SETUP_INFO\n### INFO ### Setting of NVME_USED=$NVME_USED but DENALI not set!"
    else
      echo "DENALI                  is set to: \"$DENALI\""
    fi
  fi


  ####### Print warning messages and create $snap_env_sh
  echo -e "======================================================="
  echo -e "\n=====Content of $(basename $snap_env_sh)============================"
  cat $snap_env_sh
  echo -e "======================================================="

  RC=0
  if [ -n "$SETUP_WARNING" ]; then
    RC=1
    echo -e "$SETUP_WARNING"
    echo -e "\nPlease add the required environment settings to the file $(basename $snap_env_sh)"
    echo -e "All of the variables above have to be filled with the correct values."
  fi

  if [ "$snap_env_info" == "y" ] && [ -n "$SETUP_INFO" ]; then
    echo -e "$SETUP_INFO"
  fi

  if [ -n "$SETUP_EMPTY" ]; then
    let "RC = 2 - $RC"
    echo -e "\nThe following environment variables need to get defined:$SETUP_EMPTY"
    echo -e "Please edit $(basename $snap_env_sh) and add the correct values"
  fi
  echo

  SETUP_DONE="1"
done

if [ -z "$snap_env_info" ]; then
  if [ "$0" == "bash" ]; then
    # return value in case that this file was sourced
    return $RC
  else
    # otherwise set an exit state
    exit $RC
  fi
fi
