#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#
if [ $# -gt 1 ]; then
  FPGACARD=$1
  PSL_DCP=$2

  if [ "$FPGACARD" == "N250SP" ] || [ "$FPGACARD" == "RCXVUP" ]; then
    export PSL_DCP_TYPE=$FPGACARD
  else
    if [ -n "$PSL_DCP" ]; then
      PSL_MD5=`md5sum $PSL_DCP | cut -d " " -f 1`
    else
      PSL_MD5="UNKNOWN"
    fi

    case $PSL_MD5 in
      '714ee9a2f542064ea9733639d540f562')    export PSL_DCP_TYPE="N250S";; # Version 007 built with vivado 2017.4
      '51b64ad40a3dc54ec855d7d7dfef0896')    export PSL_DCP_TYPE="ADKU3";; # rblack_PSLrev6_v174_20170122_vsec400
      '6de8dd18738e8dfd65172196de9965d6')    export PSL_DCP_TYPE="AD8K5";; # portal_20180326_r006
      'b42c543031c2878674f942e3727958d1')    export PSL_DCP_TYPE="S121B";; # wbstart_apr24, BPIx16
      '6cf320f698fd3125ad27b189fd162142')    export PSL_DCP_TYPE="S121B";; # SPIx4 32bit flash address
      'd051aa72ce08b60fd587a74a5146bf88')    export PSL_DCP_TYPE="N250S OUTDATED";;
      '5bf24f90f52e6959e8e6082245a2ac3c')    export PSL_DCP_TYPE="N250S OUTDATED";;
      '3a2d162828aed3cb271d1151be9bfdde')    export PSL_DCP_TYPE="N250S OUTDATED";; # with reset fix 20171220
      'd7196d64990594f6c267aa8192a41573')    export PSL_DCP_TYPE="N250S OUTDATED";; # with reset fix 20180212 + vivado 2017.4
      '1b1526c0d3cb61815c886f83d3b4f202')    export PSL_DCP_TYPE="ADKU3 OUTDATED";;
      'f920e532c7dfea8aa7c0f90db5b54bff')    export PSL_DCP_TYPE="ADKU3 OUTDATED";; # with reset fix 20171220
      '3fa538efab1bc3e3fabe06477445d314')    export PSL_DCP_TYPE="S121B OUTDATED";;
      '8602200acb12d2de68c2a8a95735571a')    export PSL_DCP_TYPE="S121B OUTDATED";;
      '400d13185ce03f38776d672690618b2e')    export PSL_DCP_TYPE="S121B OUTDATED";; # psl233_viv17.4_vsec400h_Feb23
      *)                                     export PSL_DCP_TYPE="UNKNOWN";;
    esac
  fi
  echo "$PSL_DCP_TYPE"

else
  echo "Missing parameters for "`basename $0`
fi
