#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#

if [ $# -eq 2 ]; then
  FPGACARD=$1
  PSL_DCP=$2
else
    exit
fi

if [ "$FPGACARD" == "N250SP" ]; then
  export PSL_DCP_TYPE=$FPGACARD
else
  PSL_MD5=`md5sum $PSL_DCP | cut -d " " -f 1`

  case $PSL_MD5 in
    '5bf24f90f52e6959e8e6082245a2ac3c')    export PSL_DCP_TYPE="N250S";;
    '3a2d162828aed3cb271d1151be9bfdde')    export PSL_DCP_TYPE="N250S";; # with reset fix 20171220
    '1b1526c0d3cb61815c886f83d3b4f202')    export PSL_DCP_TYPE="ADKU3";;    
    'f920e532c7dfea8aa7c0f90db5b54bff')    export PSL_DCP_TYPE="ADKU3";; # with reset fix 20171220
    '51b64ad40a3dc54ec855d7d7dfef0896')    export PSL_DCP_TYPE="ADKU3";; # rblack_PSLrev6_v174_20170122_vsec400
    '3fa538efab1bc3e3fabe06477445d314')    export PSL_DCP_TYPE="S121B";; 
    '8602200acb12d2de68c2a8a95735571a')    export PSL_DCP_TYPE="S121B";;
    'd051aa72ce08b60fd587a74a5146bf88')    export PSL_DCP_TYPE="N250S OUTDATED";;    
    *)                                     export PSL_DCP_TYPE="UNKNOWN";;
  esac
fi

echo "$PSL_DCP_TYPE"
