#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2016,2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#
snapdir=$(dirname $(dirname $(readlink -f "$BASH_SOURCE"))) # parent of path containing this script
currdir=`pwd`

snap_config=$snapdir/.snap_config
snap_config_sh=$snapdir/.snap_config.sh
snap_env=$snapdir/.snap_env
snap_env_sh=$snapdir/.snap_env.sh

cd $snapdir

. ./snap_config
. ./snap_env "$snap_config_sh"

cd $currdir
