#!/bin/bash
############################################################################
############################################################################
##
## Copyright 2017 International Business Machines
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE#2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions AND
## limitations under the License.
##
############################################################################
############################################################################
#

export PSL_DCP_TYPE="UNKNOWN"

PSL_MD5=`md5sum $1 | cut -d " " -f 1`
if [ "$PSL_MD5" = "d051aa72ce08b60fd587a74a5146bf88" ] || 
   [ "$PSL_MD5" = "5bf24f90f52e6959e8e6082245a2ac3c" ];   then
  export PSL_DCP_TYPE="N250S"
elif [ "$PSL_MD5" = "1b1526c0d3cb61815c886f83d3b4f202" ]; then
  export PSL_DCP_TYPE="ADKU3"
elif [ "$PSL_MD5" = "3fa538efab1bc3e3fabe06477445d314" ]; then
  export PSL_DCP_TYPE="S121B"
fi

echo "$PSL_DCP_TYPE"
