#!/bin/bash
#
# Copyright 2016, International Business Machines
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################
#
# important environment variables for running tools
# the goal is to be able to source this file and have everything set as needed


if [ ! -d "$XILINX_VIVADO" ] || [ -z "$XILINXD_LICENSE_FILE" ] || [ ! -d "$FRAMEWORK_ROOT" ]; then
  echo "Note: the following site specific variables are used by the build and sim tools"
  echo "and should be be set prior to sourcing this file:"
  echo
  echo "XILINX_VIVADO          # path to Vivado tool"
  echo "XILINXD_LICENSE_FILE"
  echo "FRAMEWORK_ROOT         # path to CAPI STREAMING FRAMEWORK root directory"
  echo
  echo "Recommended directory structure:"
  echo "FRAMEWORK_ROOT      = <your local workspace base> "
  echo "USERHOME            = \$FRAMEWORK_ROOT/$USER  # each user has his own workspace"
  echo "PSLSE_ROOT          = \$USERHOME/pslse        # PSLSE clone from github"
  echo "DONUT_ROOT          = \$USERHOME/donut        # donut clone from github"
  echo "DONUT_SOFTWARE_ROOT = \$DONUT_ROOT/software   # path to donut software "
  echo "DONUT_HARDWARE_ROOT = \$DONUT_ROOT/hardware   # path to donut hardware "
fi

####### Xilinx settings before running VIVADO and XSIM
 source $XILINX_VIVADO/settings64.sh                        # settings for SDK+HLS+docnav+vivado, does all of the above

####### Xilinx Vivado calls:
# vivado &                                                   # run Vivado GUI
# vivado -mode tcl                                           # run Vivado GUI, start at linux cmd prompt
# vivado -mode batch -source run.tcl                         # run Vivado in batch mode

####### user settings for CAPI STREAMING FRAMEWORK
if [ ! -d "$USERHOME" ]; then
  export USERHOME=$FRAMEWORK_ROOT/$USER
  echo "Setting USERHOME            to \"$USERHOME\""
else
  echo "USERHOME             is set to \"$USERHOME\""
fi

if [ ! -d "$PSLSE_ROOT" ]; then
  export PSLSE_ROOT=$USERHOME/pslse                          # used with git clone https://github.com/ibm-capi/pslse     $PSLSE_ROOT
  echo "Setting PSLSE_ROOT          to \"$PSLSE_ROOT\""
else
  echo "PSLSE_ROOT           is set to \"$PSLSE_ROOT\""
fi

if [ ! -d "$DONUT_ROOT" ]; then
  export DONUT_ROOT=$USERHOME/donut                          # used with git clone git@github.com:open-power/donut.git   $DONUT_ROOT
  echo "Setting DONUT_ROOT          to \"$DONUT_ROOT\""
else
  echo "DONUT_ROOT           is set to \"$DONUT_ROOT\""
fi

if [ ! -d "$FPGACARD" ]; then
  export FPGACARD=$FRAMEWORK_ROOT/cards/adku060_capi_1_1_release
  echo "Setting FPGACARD            to \"$FPGACARD\""
else
  echo "FPGACARD             is set to \"$FPGACARD\""
fi

if [ -z "$FPGACHIP" ]; then
  export FPGACHIP=xcku060-ffva1156-2-e
  echo "Setting FPGACHIP            to \"$FPGACHIP\""
else
  echo "FPGACHIP             is set to \"$FPGACHIP\""
fi

if [ ! -d "$DIMMTEST" ]; then
  export DIMMTEST=$FRAMEWORK_ROOT/cards/dimm_test-admpcieku3-v3_0_0
  echo "Setting CARDDIMM            to \"$DIMMTEST\""
else
  echo "DIMMTEST             is set to \"$DIMMTEST\""
fi

if [ -z "$SIMULATOR" ]; then
  export SIMULATOR=xsim                                      # xsim, questa and ncsim are supported, currently
  echo "Setting SIMULATOR           to \"$SIMULATOR\""
else
  echo "SIMULATOR            is set to \"$SIMULATOR\""
fi

if [ ! -d "$DONUT_SOFTWARE_ROOT" ]; then
  export DONUT_SOFTWARE_ROOT=$DONUT_ROOT/software
  echo "Setting DONUT_SOFTWARE_ROOT to \"$DONUT_SOFTWARE_ROOT\""
else
  echo "DONUT_SOFTWARE_ROOT  is set to \"$DONUT_SOFTWARE_ROOT\""
fi

if [ ! -d "$DONUT_HARDWARE_ROOT" ]; then
  export DONUT_HARDWARE_ROOT=$DONUT_ROOT/hardware
  echo "Setting DONUT_HARDWARE_ROOT to \"$DONUT_HARDWARE_ROOT\""
else
  echo "DONUT_HARDWARE_ROOT  is set to \"$DONUT_HARDWARE_ROOT\""
fi

echo
