## clocks ###########################################################################################

create_clock -period 3.332 -name c0_ddr4_sys_clk_p [get_ports c0_ddr4_sys_clk_p]
set_false_path -from [get_pins {*/pci_user_reset_qq_reg/C}] -to [get_pins {*/sdram_reset_m_reg/D}]
set_false_path -from [get_pins {*/pci_user_reset_q_reg/C}] -to [get_pins {*/sdram_reset_m_reg/D}]
#
##========================================================================
## DDR's IO constraints
##========================================================================
#set_property PACKAGE_PIN BB39     [get_ports c0_ddr4_act_n] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	c0_ddr4_act_n	] ;
#
#set_property PACKAGE_PIN AN36     [get_ports {c0_ddr4_adr[13]}] ;
##set_property PACKAGE_PIN AN35     [get_ports {c0_ddr4_adr[17]}] ;
#set_property PACKAGE_PIN AR36     [get_ports {c0_ddr4_adr[16]}] ;
#set_property PACKAGE_PIN AP36     [get_ports {c0_ddr4_adr[15]}] ;
#set_property PACKAGE_PIN AP35     [get_ports {c0_ddr4_adr[14]}] ;
#set_property PACKAGE_PIN AR35     [get_ports {c0_ddr4_adr[10]}] ;
#set_property PACKAGE_PIN AT36     [get_ports {c0_ddr4_adr[0]}] ;
#set_property PACKAGE_PIN AV37     [get_ports {c0_ddr4_adr[2]}] ;
#set_property PACKAGE_PIN AV36     [get_ports {c0_ddr4_adr[1]}] ;
#set_property PACKAGE_PIN AW36     [get_ports {c0_ddr4_adr[4]}] ;
#set_property PACKAGE_PIN AW35     [get_ports {c0_ddr4_adr[3]}] ;
#set_property PACKAGE_PIN AY36     [get_ports {c0_ddr4_adr[5]}] ;
#set_property PACKAGE_PIN AY35     [get_ports {c0_ddr4_adr[6]}] ;
#set_property PACKAGE_PIN BA37     [get_ports {c0_ddr4_adr[8]}] ;
#set_property PACKAGE_PIN BA40     [get_ports {c0_ddr4_adr[7]}] ;
#set_property PACKAGE_PIN BA39     [get_ports {c0_ddr4_adr[11]}] ;
#set_property PACKAGE_PIN BB40     [get_ports {c0_ddr4_adr[12]}] ;
#set_property PACKAGE_PIN BB37     [get_ports {c0_ddr4_adr[9]}] ;
#
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[13]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[17]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[16]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[15]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[14]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[10]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[0]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[2]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[1]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[4]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[3]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[5]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[6]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[8]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[7]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[11]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[12]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_adr[9]}	] ; 
#
#set_property PACKAGE_PIN AY38     [get_ports c0_ddr4_sys_clk_n] ;
#set_property PACKAGE_PIN AY37     [get_ports c0_ddr4_sys_clk_p] ;
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	c0_ddr4_sys_clk_n	] ;  
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	c0_ddr4_sys_clk_p	] ; 
#
#set_property PACKAGE_PIN AP34     [get_ports {c0_ddr4_odt[0]}] ;
##set_property PACKAGE_PIN AN34     [get_ports {c0_ddr4_odt[1]}] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_odt[1]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_odt[0]}	] ; 
#
#set_property PACKAGE_PIN AR33     [get_ports {c0_ddr4_cs_n[0]}] ;
##set_property PACKAGE_PIN AP33     [get_ports {c0_ddr4_cs_n[1]}] ;
##set_property PACKAGE_PIN AN33     [get_ports {c0_ddr4_cs_n[2]}] ;
##set_property PACKAGE_PIN AM34	   [get_ports {c0_ddr4_cs_n[3]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cs_n[3]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cs_n[1]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cs_n[2]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cs_n[0]}	] ; 
#
#set_property PACKAGE_PIN AT35     [get_ports {c0_ddr4_ba[0]}] ;
#set_property PACKAGE_PIN AT34     [get_ports {c0_ddr4_ba[1]}] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_ba[0]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_ba[1]}	] ; 
#
#set_property PACKAGE_PIN BC37     [get_ports {c0_ddr4_bg[0]}] ;
#set_property PACKAGE_PIN BC39     [get_ports {c0_ddr4_bg[1]}] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_bg[1]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_bg[0]}	] ;
#
#set_property PACKAGE_PIN AV38     [get_ports {c0_ddr4_ck_t[0]}] ;
##set_property PACKAGE_PIN AU34     [get_ports {c0_ddr4_ck_t[1]}] ;
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	{c0_ddr4_ck_t[0]}	] ; 
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	{c0_ddr4_ck_t[1]}	] ; 
#
#set_property PACKAGE_PIN AW38     [get_ports {c0_ddr4_ck_c[0]}] ;
##set_property PACKAGE_PIN AU35     [get_ports {c0_ddr4_ck_c[1]}] ;
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	{c0_ddr4_ck_c[0]}	] ; 
##set_property	IOSTANDARD		DIFF_SSTL12	[get_ports 	{c0_ddr4_ck_c[1]}	] ; 
#
#set_property PACKAGE_PIN BC38     [get_ports {c0_ddr4_cke[0]}] ;
##set_property PACKAGE_PIN BC40     [get_ports {c0_ddr4_cke[1]}] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cke[1]}	] ; 
##set_property	IOSTANDARD		SSTL12	[get_ports 	{c0_ddr4_cke[0]}	] ; 
#
#set_property PACKAGE_PIN AU31     [get_ports c0_ddr4_reset_n] ;
##set_property	IOSTANDARD		SSTL12	[get_ports 	c0_ddr4_reset_n	] ; 
#
#set_property PACKAGE_PIN BD40     [get_ports {c0_ddr4_dq[64]}] ;
#set_property PACKAGE_PIN BD39     [get_ports {c0_ddr4_dq[65]}] ;
#set_property PACKAGE_PIN BF43     [get_ports {c0_ddr4_dq[66]}] ;
#set_property PACKAGE_PIN BF42     [get_ports {c0_ddr4_dq[67]}] ;
#set_property PACKAGE_PIN BF38     [get_ports {c0_ddr4_dqs_c[8]}] ;
#set_property PACKAGE_PIN BE38     [get_ports {c0_ddr4_dqs_t[8]}] ;
#set_property PACKAGE_PIN BF41     [get_ports {c0_ddr4_dq[71]}] ;
#set_property PACKAGE_PIN BE40     [get_ports {c0_ddr4_dq[70]}] ;
#set_property PACKAGE_PIN BF37     [get_ports {c0_ddr4_dq[68]}] ;
#set_property PACKAGE_PIN BE37     [get_ports {c0_ddr4_dq[69]}] ;
#set_property PACKAGE_PIN BF40     [get_ports {c0_ddr4_dqs_c[17]}] ;
#set_property PACKAGE_PIN BF39     [get_ports {c0_ddr4_dqs_t[17]}] ;
#set_property PACKAGE_PIN AM30     [get_ports {c0_ddr4_dq[33]}] ;
#set_property PACKAGE_PIN AL30     [get_ports {c0_ddr4_dq[32]}] ;
#set_property PACKAGE_PIN AU32     [get_ports {c0_ddr4_dq[34]}] ;
#set_property PACKAGE_PIN AT32     [get_ports {c0_ddr4_dq[35]}] ;
#set_property PACKAGE_PIN AM32     [get_ports {c0_ddr4_dqs_c[4]}] ;
#set_property PACKAGE_PIN AM31     [get_ports {c0_ddr4_dqs_t[4]}] ;
#set_property PACKAGE_PIN AR32     [get_ports {c0_ddr4_dq[38]}] ;
#set_property PACKAGE_PIN AR31     [get_ports {c0_ddr4_dq[39]}] ;
#set_property PACKAGE_PIN AN32     [get_ports {c0_ddr4_dq[37]}] ;
#set_property PACKAGE_PIN AN31     [get_ports {c0_ddr4_dq[36]}] ;
#set_property PACKAGE_PIN AP31     [get_ports {c0_ddr4_dqs_c[13]}] ;
#set_property PACKAGE_PIN AP30     [get_ports {c0_ddr4_dqs_t[13]}] ;
#set_property PACKAGE_PIN AW34     [get_ports {c0_ddr4_dq[27]}] ;
#set_property PACKAGE_PIN AV34     [get_ports {c0_ddr4_dq[26]}] ;
#set_property PACKAGE_PIN AV32     [get_ports {c0_ddr4_dq[25]}] ;
#set_property PACKAGE_PIN AV31     [get_ports {c0_ddr4_dq[24]}] ;
#set_property PACKAGE_PIN AW33     [get_ports {c0_ddr4_dqs_c[3]}] ;
#set_property PACKAGE_PIN AV33     [get_ports {c0_ddr4_dqs_t[3]}] ;
#set_property PACKAGE_PIN AY31     [get_ports {c0_ddr4_dq[29]}] ;
#set_property PACKAGE_PIN AW31     [get_ports {c0_ddr4_dq[28]}] ;
#set_property PACKAGE_PIN BA35     [get_ports {c0_ddr4_dq[30]}] ;
#set_property PACKAGE_PIN BA34     [get_ports {c0_ddr4_dq[31]}] ;
#set_property PACKAGE_PIN BA33     [get_ports {c0_ddr4_dqs_c[12]}] ;
#set_property PACKAGE_PIN BA32     [get_ports {c0_ddr4_dqs_t[12]}] ;
#set_property PACKAGE_PIN AY33     [get_ports {c0_ddr4_dq[19]}] ;
#set_property PACKAGE_PIN AY32     [get_ports {c0_ddr4_dq[18]}] ;
#set_property PACKAGE_PIN BB32     [get_ports {c0_ddr4_dq[17]}] ;
#set_property PACKAGE_PIN BB31     [get_ports {c0_ddr4_dq[16]}] ;
#set_property PACKAGE_PIN BB36     [get_ports {c0_ddr4_dqs_c[2]}] ;
#set_property PACKAGE_PIN BB35     [get_ports {c0_ddr4_dqs_t[2]}] ;
#set_property PACKAGE_PIN BC33     [get_ports {c0_ddr4_dq[21]}] ;
#set_property PACKAGE_PIN BC32     [get_ports {c0_ddr4_dq[20]}] ;
#set_property PACKAGE_PIN BC34     [get_ports {c0_ddr4_dq[23]}] ;
#set_property PACKAGE_PIN BB34     [get_ports {c0_ddr4_dq[22]}] ;
#set_property PACKAGE_PIN BD31     [get_ports {c0_ddr4_dqs_c[11]}] ;
#set_property PACKAGE_PIN BC31     [get_ports {c0_ddr4_dqs_t[11]}] ;
#set_property PACKAGE_PIN BD35     [get_ports {c0_ddr4_dq[59]}] ;
#set_property PACKAGE_PIN BD34     [get_ports {c0_ddr4_dq[56]}] ;
#set_property PACKAGE_PIN BE33     [get_ports {c0_ddr4_dq[58]}] ;
#set_property PACKAGE_PIN BD33     [get_ports {c0_ddr4_dq[57]}] ;
#set_property PACKAGE_PIN BE36     [get_ports {c0_ddr4_dqs_c[7]}] ;
#set_property PACKAGE_PIN BE35     [get_ports {c0_ddr4_dqs_t[7]}] ;
#set_property PACKAGE_PIN BF33     [get_ports {c0_ddr4_dq[61]}] ;
#set_property PACKAGE_PIN BF32     [get_ports {c0_ddr4_dq[60]}] ;
#set_property PACKAGE_PIN BF35     [get_ports {c0_ddr4_dq[63]}] ;
#set_property PACKAGE_PIN BF34     [get_ports {c0_ddr4_dq[62]}] ;
#set_property PACKAGE_PIN BE32     [get_ports {c0_ddr4_dqs_c[16]}] ;
#set_property PACKAGE_PIN BE31     [get_ports {c0_ddr4_dqs_t[16]}] ;
#set_property PACKAGE_PIN AN27     [get_ports {c0_ddr4_dq[42]}] ;
#set_property PACKAGE_PIN AM27     [get_ports {c0_ddr4_dq[43]}] ;
#set_property PACKAGE_PIN AP29     [get_ports {c0_ddr4_dq[40]}] ;
#set_property PACKAGE_PIN AP28     [get_ports {c0_ddr4_dq[41]}] ;
#set_property PACKAGE_PIN AL29     [get_ports {c0_ddr4_dqs_c[5]}] ;
#set_property PACKAGE_PIN AL28     [get_ports {c0_ddr4_dqs_t[5]}] ;
#set_property PACKAGE_PIN AR28     [get_ports {c0_ddr4_dq[47]}] ;
#set_property PACKAGE_PIN AR27     [get_ports {c0_ddr4_dq[46]}] ;
#set_property PACKAGE_PIN AN29     [get_ports {c0_ddr4_dq[44]}] ;
#set_property PACKAGE_PIN AM29     [get_ports {c0_ddr4_dq[45]}] ;
#set_property PACKAGE_PIN AT30     [get_ports {c0_ddr4_dqs_c[14]}] ;
#set_property PACKAGE_PIN AR30     [get_ports {c0_ddr4_dqs_t[14]}] ;
#set_property PACKAGE_PIN AT28     [get_ports {c0_ddr4_dq[48]}] ;
#set_property PACKAGE_PIN AT27     [get_ports {c0_ddr4_dq[51]}] ;
#set_property PACKAGE_PIN AV27     [get_ports {c0_ddr4_dq[49]}] ;
#set_property PACKAGE_PIN AU27     [get_ports {c0_ddr4_dq[50]}] ;
#set_property PACKAGE_PIN AU30     [get_ports {c0_ddr4_dqs_c[6]}] ;
#set_property PACKAGE_PIN AU29     [get_ports {c0_ddr4_dqs_t[6]}] ;
#set_property PACKAGE_PIN AV29     [get_ports {c0_ddr4_dq[52]}] ;
#set_property PACKAGE_PIN AV28     [get_ports {c0_ddr4_dq[55]}] ;
#set_property PACKAGE_PIN AY30     [get_ports {c0_ddr4_dq[53]}] ;
#set_property PACKAGE_PIN AW30     [get_ports {c0_ddr4_dq[54]}] ;
#set_property PACKAGE_PIN AY28     [get_ports {c0_ddr4_dqs_c[15]}] ;
#set_property PACKAGE_PIN AY27     [get_ports {c0_ddr4_dqs_t[15]}] ;
#set_property PACKAGE_PIN AW29     [get_ports {c0_ddr4_dq[1]}] ;
#set_property PACKAGE_PIN AW28     [get_ports {c0_ddr4_dq[0]}] ;
#set_property PACKAGE_PIN BA28     [get_ports {c0_ddr4_dq[2]}] ;
#set_property PACKAGE_PIN BA27     [get_ports {c0_ddr4_dq[3]}] ;
#set_property PACKAGE_PIN BB30     [get_ports {c0_ddr4_dqs_c[0]}] ;
#set_property PACKAGE_PIN BA30     [get_ports {c0_ddr4_dqs_t[0]}] ;
#set_property PACKAGE_PIN BC27     [get_ports {c0_ddr4_dq[6]}] ;
#set_property PACKAGE_PIN BB27     [get_ports {c0_ddr4_dq[7]}] ;
#set_property PACKAGE_PIN BB29     [get_ports {c0_ddr4_dq[4]}] ;
#set_property PACKAGE_PIN BA29     [get_ports {c0_ddr4_dq[5]}] ;
#set_property PACKAGE_PIN BC26     [get_ports {c0_ddr4_dqs_c[9]}] ;
#set_property PACKAGE_PIN BB26     [get_ports {c0_ddr4_dqs_t[9]}] ;
#set_property PACKAGE_PIN BE30     [get_ports {c0_ddr4_dq[10]}] ;
#set_property PACKAGE_PIN BD30     [get_ports {c0_ddr4_dq[11]}] ;
#set_property PACKAGE_PIN BF28     [get_ports {c0_ddr4_dq[9]}] ;
#set_property PACKAGE_PIN BE28     [get_ports {c0_ddr4_dq[8]}] ;
#set_property PACKAGE_PIN BD29     [get_ports {c0_ddr4_dqs_c[1]}] ;
#set_property PACKAGE_PIN BD28     [get_ports {c0_ddr4_dqs_t[1]}] ;
#set_property PACKAGE_PIN BF27     [get_ports {c0_ddr4_dq[12]}] ;
#set_property PACKAGE_PIN BE27     [get_ports {c0_ddr4_dq[13]}] ;
#set_property PACKAGE_PIN BF30     [get_ports {c0_ddr4_dq[14]}] ;
#set_property PACKAGE_PIN BF29     [get_ports {c0_ddr4_dq[15]}] ;
#set_property PACKAGE_PIN BE26     [get_ports {c0_ddr4_dqs_c[10]}] ;
#set_property PACKAGE_PIN BD26     [get_ports {c0_ddr4_dqs_t[10]}] ;
#
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[64]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[65]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[66]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[67]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[8]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[8]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[71]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[70]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[68]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[69]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[17]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[17]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[33]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[32]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[34]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[35]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[4]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[4]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[38]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[39]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[37]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[36]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[13]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[13]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[27]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[26]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[25]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[24]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[3]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[3]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[29]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[28]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[30]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[31]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[12]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[12]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[19]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[18]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[17]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[16]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[2]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[2]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[21]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[20]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[23]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[22]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[11]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[11]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[59]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[56]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[58]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[57]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[7]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[7]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[61]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[60]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[63]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[62]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[16]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[16]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[42]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[43]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[40]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[41]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[5]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[5]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[47]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[46]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[44]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[45]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[14]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[14]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[48]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[51]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[49]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[50]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[6]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[6]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[52]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[55]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[53]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[54]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[15]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[15]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[1]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[0]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[2]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[3]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[0]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[0]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[6]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[7]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[4]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[5]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[9]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[9]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[10]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[11]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[9]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[8]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[1]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[1]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[12]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[13]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[14]}	] ; 
##set_property	IOSTANDARD		POD12	[get_ports 	{c0_ddr4_dq[15]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_c[10]}	] ; 
##set_property	IOSTANDARD		DIFF_POD12	[get_ports 	{c0_ddr4_dqs_t[10]}	] ; 
