#!/bin/bash
#
# Copyright 2017 International Business Machines
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version=1.0
program=$(basename "$0")
prgdir=$(dirname $(readlink -f "$BASH_SOURCE")) # path containing this script
snap_root=$(dirname "$prgdir")

# output formatting
bold=$(tput bold)
normal=$(tput sgr0)

# Name of global config file
build_dir="$prgdir/build"
kconfig="$prgdir/Kconfig"
config="$build_dir/config"
snap_config="$snap_root/.snap_config"
snap_config_sh="$snap_config".sh
snap_config_cflags="$snap_config".cflags
autoconf=$snap_root/software/include/autoconf.h
option=menuconfig

# Print usage message helper function
function usage() {
  echo "Usage: ${program} [OPTIONS]"
  echo "    [-o <oldconfig/menuconfig/...>] Use this as option."
  echo "    [-c <config>]        Copy results to this config file."
  echo "    [-a <autoconf>]    Location of autoconf.h."
  echo "    [-V] Print program version (${version})"
  echo "    [-h] Print this help message."
  echo "    <path-to-bit-file>"
  echo
  echo "Utility to generate vivado_hls tcl configuration file."
  echo
}

# Parse any options given on the command line
while getopts ":a:o:c:Vh" opt; do
  case ${opt} in
      a)
      autoconf=$OPTARG
      ;;
      o)
      option=$OPTARG
      ;;
      c)
      snap_config=$OPTARG
      snap_config_sh=$OPTARG.sh
      snap_config_cflags=$OPTARG.cflags
      ;;
      V)
      echo "${version}" >&2
      exit 0
      ;;
      h)
      usage;
      exit 0
      ;;
      \?)
      printf "${bold}ERROR:${normal} Invalid option: -${OPTARG}\n" >&2
      exit 1
      ;;
      :)
      printf "${bold}ERROR:${normal} Option -$OPTARG requires an argument.\n" >&2
      exit 1
      ;;
  esac
done

echo "SNAP Build Options"
echo "  Kconfig:          $kconfig"
echo "  Build directory:  $build_dir"
echo "  config:           $snap_config"
echo "  autoconf:         $autoconf"

if [ ! -e $build_dir ]; then
  echo "Cloning kconfig from github.com/guillon/kconfig into $build_dir"
  git clone https://github.com/guillon/kconfig $build_dir
fi
if [ -e $snap_config ]; then
  cp -p $snap_config $config
else
  rm -f $config
fi

cmd="make -C $build_dir -f GNUmakefile TOPDIR=. SRCDIR=. KBUILD_KCONFIG=$kconfig $option"

echo "Executing:"
echo "  $cmd"
$cmd

echo "Generating SNAP config files $snap_config, $snap_config_sh and $snap_config_cflags ..."
cp $config $snap_config
cat $snap_config | sed 's/^\([^#].*\)/export \1/' | tr -d '"' > $snap_config_sh
chmod +x $snap_config_sh
cat $snap_config | tr -d '"' | sed 's/^\([^#].*\)/SNAP_CFLAGS += "-DCONFIG_\1"/' > $snap_config_cflags
echo "Generation of SNAP config files done."
echo

if [ -f $build_dir/include/linux/autoconf.h ]; then
  echo "Copy resulting $autoconf file ..."
  cp $build_dir/include/linux/autoconf.h $autoconf
fi
